"""SportyTips web server.

Connects the SportyTips website to:
    main.py
    smart_ticket.py
    sportybet_provider.py

Important:
- smart_ticket.py is explicitly imported here.
- /api/chat is supported.
- /api/build is supported.
- SportyBet booking codes are generated by sportybet_provider.py.
- No fake booking codes are created here.
"""

import base64
import html
import importlib
import json
import os
import queue
import re
import threading
import time

from flask import Flask, Response, jsonify, request, send_from_directory


# ============================================================
# SETTINGS
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

LAUNCHER_MODULE = os.getenv(
    "LAUNCHER_MODULE",
    "launcher",
)

RATE_LIMIT = 8
RATE_WINDOW = 60


# ============================================================
# IMPORT BOT
# ============================================================

bot = importlib.import_module("main")


# ============================================================
# IMPORTANT:
# LOAD SMART TICKET AFTER MAIN
#
# smart_ticket.py replaces:
#     bot.prediction_ticket_flow
#
# This import MUST happen.
# ============================================================

SMART_TICKET_ERROR = None

try:
    smart_ticket = importlib.import_module(
        "smart_ticket"
    )
    SMART_TICKET_LOADED = True

except Exception as exc:
    smart_ticket = None
    SMART_TICKET_LOADED = False
    SMART_TICKET_ERROR = str(exc)

    print(
        "WARNING: smart_ticket.py failed to load:"
    )
    print(exc)


# ============================================================
# OPTIONAL MODULES
# ============================================================

try:
    launcher = importlib.import_module(
        LAUNCHER_MODULE
    )
except Exception as exc:
    launcher = None
    print(
        "WARNING: launcher.py failed to load:",
        exc,
    )


try:
    upgrades = importlib.import_module(
        "upgrades"
    )
except Exception:
    upgrades = None


# ============================================================
# WEB MESSAGE QUEUE
# ============================================================

_ctx = threading.local()


def _emit(item):
    q = getattr(
        _ctx,
        "q",
        None,
    )

    if q is not None:
        q.put(item)


# ============================================================
# HIDE INTERNAL/API MESSAGES
# ============================================================

HIDE_LINES = re.compile(
    r"""
    API-Football
    |API limit
    |API problem
    |API requests
    |Daily API
    |Booking code failed
    |plan only allows
    """,
    re.I | re.X,
)


def _rebrand(text):
    text = re.sub(
        r"SamuelBet\s*(<span[^>]*>)\s*AI\s*(</span>)",
        r"Sporty\1Tips\2",
        text,
    )

    text = text.replace(
        "SamuelBet AI",
        "SportyTips",
    )

    text = text.replace(
        "SamuelBet",
        "SportyTips",
    )

    return text


def web_send_message(
    chat_id,
    text,
):
    text = str(text or "")

    kept = []

    for line in text.split("\n"):
        if not HIDE_LINES.search(line):
            kept.append(line)

    cleaned = "\n".join(
        kept
    ).strip()

    cleaned = re.sub(
        r"\n{3,}",
        "\n\n",
        cleaned,
    )

    if not cleaned:
        cleaned = (
            "I couldn't get that right now. "
            "Please try again in a minute."
        )

    cleaned = (
        cleaned
        .replace("&#x27;", "'")
        .replace("&#39;", "'")
        .replace("&quot;", '"')
    )

    _emit(
        {
            "type": "text",
            "html": _rebrand(cleaned),
        }
    )


def web_send_photo(
    chat_id,
    png,
    caption="",
):
    try:
        encoded = base64.b64encode(
            png
        ).decode("ascii")

        _emit(
            {
                "type": "image",
                "data": encoded,
                "caption": caption or "",
            }
        )

    except Exception as exc:
        print(
            "Photo send failed:",
            exc,
        )


# ============================================================
# REPLACE TELEGRAM OUTPUT
# ============================================================

bot.send_message = web_send_message

bot.telegram_request = (
    lambda method, params=None:
    {
        "ok": True,
        "result": [],
    }
)

if launcher is not None:
    try:
        launcher.send_photo = web_send_photo
    except Exception:
        pass


# ============================================================
# FLASK
# ============================================================

app = Flask(
    __name__,
    static_folder=BASE_DIR,
)


# ============================================================
# RATE LIMIT
# ============================================================

_hits = {}


def client_ip():
    forwarded = request.headers.get(
        "X-Forwarded-For",
        "",
    )

    if forwarded:
        return (
            forwarded
            .split(",")[0]
            .strip()
        )

    return (
        request.remote_addr
        or "?"
    )


def too_fast(
    key,
    limit=RATE_LIMIT,
):
    now = time.time()

    recent = [
        timestamp
        for timestamp in _hits.get(
            key,
            [],
        )
        if now - timestamp < RATE_WINDOW
    ]

    if len(recent) >= limit:
        _hits[key] = recent
        return True

    recent.append(now)

    _hits[key] = recent

    return False


# ============================================================
# ONLY ONE TICKET BUILD AT A TIME
# ============================================================

RUN_LOCK = threading.Lock()

_active_sessions = set()


# ============================================================
# RUN BOT
# ============================================================

def run_turn(
    session,
    text,
    q,
):
    _ctx.q = q

    try:

        with RUN_LOCK:

            bot.handle_text(
                session,
                text,
            )

    except Exception as exc:

        print(
            "Ticket error:",
            exc,
        )

        q.put(
            {
                "type": "text",
                "html": (
                    "❌ "
                    + html.escape(
                        str(exc)
                    )
                ),
            }
        )

    finally:

        _active_sessions.discard(
            session
        )

        q.put(None)

        try:
            del _ctx.q
        except Exception:
            pass


def start_turn(
    session,
    text,
):
    # Same user already building.
    if session in _active_sessions:

        return (
            None,
            (
                jsonify(
                    error=(
                        "I'm still building "
                        "your ticket. "
                        "Wait for it to finish."
                    )
                ),
                429,
            ),
        )

    # Another ticket is being built.
    if RUN_LOCK.locked():

        return (
            None,
            (
                jsonify(
                    error=(
                        "SportyTips is still "
                        "building another ticket. "
                        "Please wait for it to finish."
                    )
                ),
                429,
            ),
        )

    _active_sessions.add(
        session
    )

    q = queue.Queue()

    thread = threading.Thread(
        target=run_turn,
        args=(
            session,
            text,
            q,
        ),
        daemon=True,
        name="sportytips-ticket",
    )

    thread.start()

    return q, None


# ============================================================
# STREAM RESPONSE
# ============================================================

def stream_response(q):

    def stream():

        while True:

            try:

                item = q.get(
                    timeout=20
                )

            except queue.Empty:

                # Keep Render/browser connection alive.
                yield "\n"
                continue

            if item is None:
                break

            yield (
                json.dumps(
                    item,
                    ensure_ascii=False,
                )
                + "\n"
            )

    return Response(
        stream(),
        mimetype="application/x-ndjson",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


# ============================================================
# WEBSITE PAGES
# ============================================================

@app.get("/")
def home_page():

    path = os.path.join(
        BASE_DIR,
        "home.html",
    )

    if os.path.exists(path):
        return send_from_directory(
            BASE_DIR,
            "home.html",
        )

    return (
        "SportyTips is running. "
        "home.html is missing.",
        404,
    )


@app.get("/index.html")
def index_page():

    path = os.path.join(
        BASE_DIR,
        "index.html",
    )

    if os.path.exists(path):
        return send_from_directory(
            BASE_DIR,
            "index.html",
        )

    return (
        "index.html is missing.",
        404,
    )


@app.get("/chat")
def chat_page():

    path = os.path.join(
        BASE_DIR,
        "index.html",
    )

    if os.path.exists(path):
        return send_from_directory(
            BASE_DIR,
            "index.html",
        )

    return (
        "index.html is missing.",
        404,
    )


# ============================================================
# HEALTH
# ============================================================

@app.get("/health")
def health():

    provider = getattr(
        bot,
        "SPORTYBET_PROVIDER",
        None,
    )

    return jsonify(
        {
            "status": "ok",
            "sportytips": True,
            "sportybet": provider is not None,
            "smart_ticket": SMART_TICKET_LOADED,
            "smart_ticket_error": (
                SMART_TICKET_ERROR
                if not SMART_TICKET_LOADED
                else None
            ),
        }
    )


# ============================================================
# MAIN CHAT API
# ============================================================

@app.post("/api/chat")
def chat():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    text = str(
        data.get(
            "message",
            "",
        )
    ).strip()

    session = str(
        data.get(
            "session",
            "",
        )
    ).strip()

    text = text[:500]

    session = session[:64]

    if not text:
        return jsonify(
            error="Empty message."
        ), 400

    if not session:
        return jsonify(
            error="Missing session."
        ), 400

    if too_fast(
        client_ip()
    ):
        return jsonify(
            error=(
                "Slow down. "
                "Try again in a minute."
            )
        ), 429

    q, busy = start_turn(
        session,
        text,
    )

    if busy:
        return busy

    return stream_response(q)


# ============================================================
# /api/build
#
# Some versions of the frontend use /api/build
# instead of /api/chat.
#
# This accepts:
#   message
#   text
#   prompt
#   spec
#
# So the frontend does not break.
# ============================================================

@app.post("/api/build")
def api_build():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    text = ""

    for key in (
        "message",
        "text",
        "prompt",
    ):

        value = data.get(key)

        if value:
            text = str(value).strip()
            break

    # If frontend sends an object called "spec",
    # convert it into a simple natural-language request.
    if not text and isinstance(
        data.get("spec"),
        dict,
    ):

        spec = data["spec"]

        parts = []

        target = (
            spec.get("target_odds")
            or spec.get("odds")
            or spec.get("target")
        )

        picks = (
            spec.get("picks")
            or spec.get("count")
            or spec.get("legs")
        )

        window = (
            spec.get("window")
            or "today"
        )

        risk = (
            spec.get("risk")
            or "normal"
        )

        straight = spec.get(
            "straight_win",
            False,
        )

        if straight:
            parts.append(
                "straight win"
            )

        if target:
            parts.append(
                f"{target} odds"
            )

        elif picks:
            parts.append(
                f"best {picks} picks"
            )

        else:
            parts.append(
                "best 5 picks"
            )

        parts.append(
            str(window)
        )

        if risk:
            parts.append(
                str(risk)
            )

        text = " ".join(parts)

    if not text:
        return jsonify(
            error="Empty build request."
        ), 400

    session = str(
        data.get(
            "session",
            "",
        )
    ).strip()[:64]

    if not session:
        return jsonify(
            error="Missing session."
        ), 400

    if too_fast(
        client_ip()
    ):
        return jsonify(
            error=(
                "Slow down. "
                "Try again in a minute."
            )
        ), 429

    q, busy = start_turn(
        session,
        text[:500],
    )

    if busy:
        return busy

    return stream_response(q)


# ============================================================
# STRAIGHT WIN BUTTON
# ============================================================

@app.post("/api/straight_win")
def api_straight_win():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    window = str(
        data.get(
            "window",
            "today",
        )
    ).lower()

    session = str(
        data.get(
            "session",
            "",
        )
    ).strip()[:64]

    if window not in (
        "today",
        "long",
    ):
        return jsonify(
            error="Unknown window."
        ), 400

    if not session:
        return jsonify(
            error="Missing session."
        ), 400

    if too_fast(
        client_ip()
    ):
        return jsonify(
            error=(
                "Slow down. "
                "Try again in a minute."
            )
        ), 429

    if window == "long":
        text = (
            "straight win long ticket"
        )
    else:
        text = (
            "straight win today"
        )

    q, busy = start_turn(
        session,
        text,
    )

    if busy:
        return busy

    return stream_response(q)


# ============================================================
# SIMPLE CODE VALIDATION
# ============================================================

CODE_OK = re.compile(
    r"^[A-Z0-9]{5,12}$"
)


# ============================================================
# GENERIC TICKET TOOL
# ============================================================

def _ticket_tool(
    work
):
    if too_fast(
        client_ip()
    ):
        return jsonify(
            error=(
                "Slow down. "
                "Try again in a minute."
            )
        ), 429

    try:
        result = work()

        if result is None:
            result = {}

        return jsonify(result)

    except Exception as exc:

        print(
            "Ticket tool error:",
            exc,
        )

        return jsonify(
            error=str(exc)[:300]
        ), 500


# ============================================================
# CHECK CODE
#
# This does NOT invent or validate a code locally.
# It simply makes sure the format is reasonable.
# ============================================================

@app.post("/api/check")
def api_check():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    code = str(
        data.get(
            "code",
            "",
        )
    ).strip().upper()

    if not code:
        return jsonify(
            error="Enter a SportyBet code."
        ), 400

    if not CODE_OK.match(code):
        return jsonify(
            error="Invalid SportyBet code format."
        ), 400

    return jsonify(
        {
            "ok": True,
            "code": code,
            "message": (
                "Code format looks valid. "
                "Open it through SportyBet "
                "to verify the ticket."
            ),
        }
    )


# ============================================================
# EDIT / SAFER
#
# These routes keep the frontend from receiving 404.
# They send the request back through the normal
# SportyTips ticket engine.
# ============================================================

@app.post("/api/edit")
def api_edit():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    session = str(
        data.get(
            "session",
            "",
        )
    ).strip()[:64]

    message = str(
        data.get(
            "message",
            data.get(
                "text",
                "",
            ),
        )
    ).strip()

    if not session:
        return jsonify(
            error="Missing session."
        ), 400

    if not message:
        return jsonify(
            error="Tell SportyTips what to change."
        ), 400

    if too_fast(
        client_ip()
    ):
        return jsonify(
            error="Slow down."
        ), 429

    q, busy = start_turn(
        session,
        message[:500],
    )

    if busy:
        return busy

    return stream_response(q)


@app.post("/api/safer")
def api_safer():

    data = (
        request.get_json(
            silent=True
        )
        or {}
    )

    session = str(
        data.get(
            "session",
            "",
        )
    ).strip()[:64]

    if not session:
        return jsonify(
            error="Missing session."
        ), 400

    message = (
        "Make this ticket safer. "
        "Use SportyBet selections only. "
        "Avoid DNB, negative handicaps and "
        "under selections."
    )

    if too_fast(
        client_ip()
    ):
        return jsonify(
            error="Slow down."
        ), 429

    q, busy = start_turn(
        session,
        message,
    )

    if busy:
        return busy

    return stream_response(q)


# ============================================================
# START SERVER
# ============================================================

if __name__ == "__main__":

    provider = getattr(
        bot,
        "SPORTYBET_PROVIDER",
        None,
    )

    print(
        "======================================"
    )

    print(
        "SportyTips starting..."
    )

    print(
        "SportyBet:",
        bool(provider),
    )

    print(
        "Smart ticket:",
        SMART_TICKET_LOADED,
    )

    if SMART_TICKET_ERROR:
        print(
            "Smart ticket error:",
            SMART_TICKET_ERROR,
        )

    print(
        "======================================"
    )

    app.run(
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "8000",
            )
        ),
        threaded=True,
    )